export {default as Home } from './Home'
export {default as Login } from './Login'
export {default as Register } from './Register'
export {default as Courses } from './Courses'
export {default as SenseiDashboard } from './SenseiDashboard'
export {default as StudentDashboard } from './StudentDashboard'